#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times plus a "Hi" after the 9th iteration

COUNTER=1
while [  $COUNTER -lt 21 ]; do
    case $COUNTER in
	4)
	    echo $COUNTER
	    echo bad luck from China
	    let COUNTER=COUNTER+1
	    ;;
	4)
	    echo $COUNTER
	    echo bad luck from Japan
	    let COUNTER=COUNTER+1
	    ;;
	17)
            echo $COUNTER
            echo bad luck from Italy
            let COUNTER=COUNTER+1
	    ;;
	*)
            echo $COUNTER
            let COUNTER=COUNTER+1
    esac
done
