#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times plus a "Hi" after the 9th iteration

HOUR=0
while [  $HOUR -lt 12 ]; do
    echo Hour: $HOUR
    MINUTE=1
    let HOUR=HOUR+1
    while [ $MINUTE -lt 60 ]; do
	echo $MINUTE
	let MINUTE=MINUTE+1
    done
done

