#!/usr/bin/env bash
# This script is displaying the time of a day in hours and minutes

HOUR=0
while [  $HOUR -lt 12 ]; do
    echo Hour: $HOUR
    MINUTE=1
    let HOUR=HOUR+1
    while [ $MINUTE -lt 60 ]; do
	echo $MINUTE
	let MINUTE=MINUTE+1
    done
done

