#!/usr/bin/env bash
#Bash script installs nginx
apt-get -y install nginx
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.txt
echo "Holberton School" > /usr/share/nginx/html/index.html
service nginx restart
