#!/usr/bin/env bash
# Configure Nginx server so that redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
new_string="location /redirect_me/ {\nrewrite ^/(.*) http://https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}"
sed -i "301 $new_string" /etc/nginx/sites-avaiable/default
sudo service nginx restart
