#!/usr/bin/env bash
# Configure Nginx server so that redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.txt
echo "Holberton School" > /usr/share/nginx/html/index.html
new_string=".rules\n\t\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n"
sed -i "s/.rules/$new_string/" /etc/nginx/sites-available/default
service nginx restart
